homebrew_installed_packages:
  - coreutils
  - dockutil
  - git
  - go
  - gpg
  - hub
  - hugo
  - imagemagick
  - java11
  - macvim
  - mas
  - pngcrush
  - rsync
  - tmux
  - watch
  - wget
  - zsh-completions

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alfred
  - adobe-digital-editions
  - android-studio
  - autodesk-fusion360
  - calibre
  - discord
  - gimp
  - google-chrome
  - inkscape
  - intel-haxm
  - iterm2
  - libreoffice
  - macpass
  - meshmixer
  - mouse-fix
  - nextcloud
  - notion
  - openscad
  - rightzoom
  - ultimaker-cura
  - virtualbox
  - virtualbox-extension-pack
  - vlc
  - wkhtmltopdf
  - xquartz

mas_installed_apps:
  - { id: 425424353, name: "The Unarchiver" }

gem_packages: []

dockitems_remove:
  - Launchpad
  - Safari
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - TV
  - Music
  - Podcasts
  - News
  - App Store
  - System Preferences

dockitems_persist:
  - name: Google Chrome
    path: /Applications/Google Chrome.app
  - name: iTerm
    path: /Applications/iTerm.app



