#!/usr/bin/env ansible-playbook --ask-become-pass
---
- hosts: all

  vars_files:
    - config.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      tags: ['dock']
    - role: appsettings
      tags: ['appsettings']

  tasks:
    - name: Link Java
      become: yes
      command: ln -sfn /usr/local/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk
      tags: ['homebrew']

